# Generated by Django 2.2 on 2020-03-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_note_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_title',
            field=models.CharField(max_length=50),
        ),
    ]
