# Generated by Django 2.2 on 2020-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_auto_20200313_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
