# Generated by Django 2.2 on 2020-03-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_auto_20200319_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
